import binaryToDecimal from './binaryToDecimal';

const MAX_HEX = 255;

/**
 * Convert the decimal reference color to Hex Color
 * @param colorBitsFactor The factor of color in bits (previouly generated by hexToBpp())
 * @param maxBitsToStore Bits used to store the color data 2, 4, 8
 */
const bppToHex = (colorBitsFactor: number, maxBitsToStore: number) => {
  const maxBits = Array(maxBitsToStore).fill('1').join('');
  const bitsMaxSuportedValue = binaryToDecimal(maxBits);
  const avaragePerColorFactor = MAX_HEX / bitsMaxSuportedValue;
  return avaragePerColorFactor * colorBitsFactor;
};

export default bppToHex;
