import path from 'path';

/**
 * Wav file with the follow bits: 0100000101101110011110010010000011111111.
 */
export const simpleFile = {
  bits: '0100000101101110011110010010000011111111',
  wavFile: path.join(__dirname, 'simpleFile.wav'),
};

/**
 * A WAV file containing bits generated by DecimalNumber loader.
 */
export const decimalNumber29Wav = {
  bits: '0000000000011101',
  wavFile: path.join(__dirname, 'decimalNumber29.wav'),
};

/**
 * Calibration Circle
 */
export const calibrationCircleBmp = {
  bmpFile: path.join(__dirname, 'calibration_circle.bmp'),
};
